# Objectif : Créer un pipeline CI qui :
# 1. Se déclenche sur push vers main ET sur pull_request
# 2. Récupère le code
# 3. Installe Python 3.11
# 4. Installe les dépendances
# 5. Lance les tests pytest

name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main


# Permissions minimales (bonne pratique sécurité)
permissions:
  contents: read

jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-24.04
    steps:
      - name: récupération du code
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0

      - name: installation de Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.11

      - name: installation des dépendances
        run: pip install -r requirements.txt

      - name: lancement des tests
        run: pytest
